# Generated by Django 5.0.3 on 2024-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_unique_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('company_asset_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('asset_category', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_model', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_condition', models.CharField(blank=True, default='new', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_unique_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('company_employee_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_department', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_cell_no', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
