# Generated by Django 5.0.3 on 2024-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_unique_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('company_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(auto_now=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('assigned_asset_condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
