# Generated by Django 5.0.3 on 2024-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_companyemployeeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='asset_status',
            field=models.CharField(blank=True, default='free', max_length=100, null=True),
        ),
    ]
