# Generated by Django 5.0.3 on 2024-03-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_companyasset_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployeeasset',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
