# Generated by Django 5.0.3 on 2024-03-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_companyemployeeasset_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployeeasset',
            name='assigned_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 16, 15, 47, 20, 617685, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
