# Generated by Django 5.0.3 on 2024-03-16 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_companyemployeeasset_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployeeasset',
            name='status',
            field=models.CharField(blank=True, default='assigned', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployeeasset',
            name='assigned_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 16, 16, 41, 20, 717467, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
